name: Makefile CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: configure
      run: ./
    - name: Install dependencies
      run: make
    - name: Run check
      run: make run
    - name: Run clean
      run: make clean
